# Generated by Django 4.1.3 on 2022-11-23 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cname", models.CharField(max_length=30)),
                (
                    "createdat",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022,
                            11,
                            23,
                            14,
                            6,
                            52,
                            636202,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("updateat", models.DateTimeField(blank=True, null=True)),
                ("createdby", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectname", models.CharField(max_length=30)),
                ("client", models.CharField(max_length=30)),
                ("users", models.CharField(max_length=300)),
                (
                    "createdat",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2022,
                            11,
                            23,
                            14,
                            6,
                            52,
                            636202,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("updateat", models.DateTimeField(blank=True, null=True)),
                ("createdby", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=30)),
                ("lname", models.CharField(max_length=30)),
                ("username", models.CharField(max_length=20)),
                ("userpass", models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(name="Login",),
    ]
