# Generated by Django 4.1.3 on 2022-11-23 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_client_project_users_delete_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="createdat",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 23, 14, 7, 1, 324512, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="createdat",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 23, 14, 7, 1, 324512, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
