# Generated by Django 4.1.3 on 2022-11-23 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_alter_client_createdat_alter_project_createdat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client", old_name="cname", new_name="client_name",
        ),
        migrations.RenameField(
            model_name="project", old_name="projectname", new_name="project_name",
        ),
        migrations.RenameField(model_name="users", old_name="fname", new_name="job",),
        migrations.RenameField(model_name="users", old_name="lname", new_name="name",),
        migrations.AlterField(
            model_name="client",
            name="createdat",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 23, 14, 19, 19, 384186, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="createdat",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 23, 14, 19, 19, 384186, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
