# Generated by Django 4.1.3 on 2022-11-23 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_client_createdat_alter_client_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='createdat',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 18, 49, 7, 267497, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='createdat',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 18, 49, 7, 267497, tzinfo=datetime.timezone.utc)),
        ),
    ]
