# Generated by Django 4.1.3 on 2022-11-24 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0025_alter_client_createdat_alter_project_createdat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="createdat",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 24, 11, 7, 35, 607620, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="createdat",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 11, 24, 11, 7, 35, 607620, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.RemoveField(model_name="project", name="users",),
        migrations.AddField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(to="app1.users"),
        ),
    ]
